### PR TITLE
pymoo 0.6

### PR DESCRIPTION
**Pull request by RobinGRAPIN**
I modified the code and tutorials so that they work with the latest version of pymoo

### CODE REVIEW

**Comment by relf** [comment]
Thanks. It seems it changes some results 

```bash
FAILED tests/test_moo.py::TestMOO::test_train_pts_known - AssertionError: 2.036188329071277 not less than 1.5 
```

Not sure we can do anything, just relax the test tolerance to make it pass.

**Comment by RobinGRAPIN** [comment]
Hello, it's because I drastically reduced the number of optimization steps in test functions to shorten the testing time, as the goal is more to see that there is no crash than to assert the precision of the method. I will finish these modifications next week :)

**Comment by RobinGRAPIN** [comment]
I still don't have the reviewer's role so I let you validate this merge !

**Comment by RobinGRAPIN** [comment]
@relf

**Review by relf — CHANGES_REQUESTED** [review]
Thanks! If I am not mistaken, it does not work with `pymoo 0.5` anymore (and `Python 3.6` is obsolete), so I think you should update the `setup.py` with:
```
    python_requires=">=3.7",
    install_requires=["smt", "pymoo>=0.6.0"]
```
Maybe you could also bump the smoot version: `version = 0.2.0` and also fix the title of the PR with `pymoo 0.6`.

**Pull request merged**
